### ISSUE TITLE
[BUG] While the mod is installed, Mission Mode cannot be joined.  Players kicked with error message: "Client requested equality check too soon"

### ISSUE THREAD

**Issue by alch-emi** [dakkhuza/MoreLevelContent#1]
## Bug Description & Context

When starting a game in mission mode, any players who attempt to join the game will be kicked with an unhelpful error message.

In particular, the server will show the error message "Client requested equality check too soon!", and the player will see either that message again, or something about failing authentication.

This issue can be found described and solved [in the bugs thread on Steam](https://steamcommunity.com/workshop/filedetails/discussion/2814493175/3416558908184925936/?ctp=5#c3827537848333639505), but I'm posting it here as well because it took me a long time to actually find the solution :​p

While in hindsight this behavior makes sense, it was really inexplicable and puzzling, especially because a google search for that error turns up exactly zero results.  If nothing else, I'm hoping that this issue gets indexed by Google and other people who encounter this error are able to figure out their mistake quicker.

## Expected Behavior:

I think it'd be very nice if either:
- The server and client were shown an error message which more accurately described the problem.  Even if this means just kicking the player from the game with a custom error message and printing something to the console, it would make the problem a lot easier to notice and diagnose (it definitely would have saved me an hour or so :sweat_smile:)
- The server somehow disable mission mode now that it isn't supported.

## Steps to recreate:

- Install MoreLevelContent correctly on a dedicated server
- Have a player join with all content correctly installed on their client as well
- Start a mission.

## Solution

If you're encountering this bug, just start the game in campaign mode rather than mission mode.

**Comment by dakkhuza** [comment]
Thanks for this report! I totally missed this, however I've now added this to both the main page on the workshop as well as the FAQ. I've also updated the readme on this github and a future version will block access to mission mode while the mod is installed.
